version: '3.4'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    container_name: sql-server
    user: 'root'
    volumes:
      - /home/bfranco/docker/sql/data/:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=72130870aA
    ports:
      - 1433:1433

volumes:
  sql-server-data: