# Generated by Django 5.0.9 on 2024-10-08 05:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('created_by', models.TextField(max_length=30, verbose_name='Creado por')),
                ('updated_by', models.TextField(max_length=30, verbose_name='Actualizado por')),
                ('deleted_by', models.TextField(max_length=30, verbose_name='Eliminado por')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Dashboard ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'Dashboard',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDashboard',
            fields=[
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('updated_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Actualización')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('created_by', models.TextField(max_length=30, verbose_name='Creado por')),
                ('updated_by', models.TextField(max_length=30, verbose_name='Actualizado por')),
                ('deleted_by', models.TextField(max_length=30, verbose_name='Eliminado por')),
                ('id', models.IntegerField(blank=True, db_index=True, verbose_name='Dashboard ID')),
                ('title', models.CharField(max_length=60, verbose_name='Título')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dashboard',
                'verbose_name_plural': 'historical Dashboards',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
