# Generated by Django 5.0.9 on 2024-10-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trello_B', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='deleted_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Eliminación'),
        ),
    ]
