# Generated by Django 5.0.9 on 2024-10-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trello_B', '0003_alter_dashboard_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Actualizado por'),
        ),
        migrations.AlterField(
            model_name='historicaldashboard',
            name='created_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='historicaldashboard',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Eliminado por'),
        ),
        migrations.AlterField(
            model_name='historicaldashboard',
            name='updated_by',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Actualizado por'),
        ),
    ]
